HistoryKey: '聚合数据-历史上的今天Key'
HistoryURL: 'http://v.juhe.cn/todayOnhistory/queryEvent.php'

NewsKey: '聚合数据-新闻Key'
NewsURL: 'http://v.juhe.cn/toutiao/index'

LunarKey: '聚合数据-万年历Key'
LunarURL: 'http://v.juhe.cn/calendar/day'

WeatherKEY: '心知天气Key'
WeatherUID: '心知天气UID'
currentWeatherAPI: 'https://api.seniverse.com/v3/weather/now.json'
dailyAPI: 'https://api.seniverse.com/v3/weather/daily.json'
AQIAPI: 'https://api.seniverse.com/v3/air/now.json'
suggestionAPI: 'https://api.seniverse.com/v3/life/suggestion.json'