client_id: "client id"  # your client_id
client_secret: "client secret"  # your client_secret
redirect: "redirect uri, suggest :http://localhost:8000/callback"
refresh_token: "refresh key"

scopes:  # permission
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
authority: "https://login.microsoftonline.com/common"
graph_api: "https://graph.microsoft.com/v1.0"

